name: projeto-markovitz
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db-projeto-markovitz
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./server/db/db_data:/var/lib/postgresql/data
  
volumes:
  db_data: